apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: preparr-test
spec:
  type: NodePort
  selector:
    app: prowlarr
  ports:
    - name: webui
      port: 9696
      targetPort: 9696
      nodePort: 30696
    - name: health
      port: 9001
      targetPort: 9001
      nodePort: 31003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: preparr-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      initContainers:
      - name: preparr-init
        image: preparr:latest
        imagePullPolicy: Never
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres123"
        - name: POSTGRES_DB
          value: "servarr"
        - name: SERVARR_URL
          value: "http://prowlarr:9696"
        - name: SERVARR_TYPE
          value: "prowlarr"
        - name: SERVARR_ADMIN_USER
          value: "admin"
        - name: SERVARR_ADMIN_PASSWORD
          value: "adminpass"
        - name: SERVARR_API_KEY
          value: "c04914c6bfad445a3edc23e5edbca4d1"
        - name: CONFIG_PATH
          value: "/config/prowlarr-config.json"
        command: ["bun", "run", "dist/index.js", "--init"]
        volumeMounts:
        - name: prowlarr-config-volume
          mountPath: /config
        - name: prowlarr-config-file
          mountPath: /config/prowlarr-config.json
          subPath: prowlarr-config.json
      containers:
      - name: prowlarr
        image: linuxserver/prowlarr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "UTC"
        ports:
        - containerPort: 9696
        volumeMounts:
        - name: prowlarr-config-volume
          mountPath: /config
        readinessProbe:
          httpGet:
            path: /api/v1/system/status
            port: 9696
            httpHeaders:
            - name: X-Api-Key
              value: "c04914c6bfad445a3edc23e5edbca4d1"
          initialDelaySeconds: 60
          periodSeconds: 10
      - name: preparr-sidecar
        image: preparr:latest
        imagePullPolicy: Never
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres123"
        - name: POSTGRES_DB
          value: "prowlarr_main"
        - name: SERVARR_URL
          value: "http://localhost:9696"
        - name: SERVARR_TYPE
          value: "prowlarr"
        - name: SERVARR_ADMIN_USER
          value: "admin"
        - name: SERVARR_ADMIN_PASSWORD
          value: "adminpass"
        - name: SERVARR_API_KEY
          value: "c04914c6bfad445a3edc23e5edbca4d1"
        - name: CONFIG_PATH
          value: "/config/prowlarr-config.json"
        - name: CONFIG_WATCH
          value: "true"
        - name: CONFIG_RECONCILE_INTERVAL
          value: "30"
        - name: HEALTH_PORT
          value: "9001"
        - name: LOG_LEVEL
          value: "debug"
        - name: QBITTORRENT_URL
          value: "http://qbittorrent:8080"
        - name: QBITTORRENT_USER
          value: "admin"
        - name: QBITTORRENT_PASSWORD
          value: "adminpass"
        command: ["bun", "run", "dist/index.js"]
        ports:
        - containerPort: 9001
        volumeMounts:
        - name: prowlarr-config-volume
          mountPath: /config
        - name: prowlarr-config-file
          mountPath: /config/prowlarr-config.json
          subPath: prowlarr-config.json
        readinessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: prowlarr-config-volume
        emptyDir: {}
      - name: prowlarr-config-file
        configMap:
          name: prowlarr-config