apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: preparr-test
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: bittorrent
      port: 6881
      targetPort: 6881
      nodePort: 30881
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: preparr-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      initContainers:
      - name: preparr-init
        image: preparr:latest
        imagePullPolicy: Never
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres123"
        - name: POSTGRES_DB
          value: "servarr"
        - name: SERVARR_TYPE
          value: "qbittorrent"
        - name: QBITTORRENT_USER
          value: "admin"
        - name: QBITTORRENT_PASSWORD
          value: "adminpass2"
        - name: SERVARR_ADMIN_USER
          value: "admin"
        - name: SERVARR_ADMIN_PASSWORD
          value: "adminpass"
        - name: QBITTORRENT_URL
          value: "http://qbittorrent:8080"
        - name: CONFIG_PATH
          value: "/config/qbittorrent-config.json"
        command: ["bun", "run", "dist/index.js", "--init"]
        volumeMounts:
        - name: qbittorrent-config-volume
          mountPath: /config
        - name: qbittorrent-config-file
          mountPath: /config/qbittorrent-config.json
          subPath: qbittorrent-config.json
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "UTC"
        - name: WEBUI_PORT
          value: "8080"
        ports:
        - containerPort: 8080
        - containerPort: 6881
        volumeMounts:
        - name: qbittorrent-config-volume
          mountPath: /config
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: qbittorrent-config-volume
        emptyDir: {}
      - name: qbittorrent-config-file
        configMap:
          name: qbittorrent-config