apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: preparr-test
spec:
  type: NodePort
  selector:
    app: radarr
  ports:
    - name: webui
      port: 7878
      targetPort: 7878
      nodePort: 30878
    - name: health
      port: 9001
      targetPort: 9001
      nodePort: 31002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: preparr-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      initContainers:
      - name: preparr-init
        image: preparr:latest
        imagePullPolicy: Never
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres123"
        - name: POSTGRES_DB
          value: "servarr"
        - name: SERVARR_URL
          value: "http://radarr:7878"
        - name: SERVARR_TYPE
          value: "radarr"
        - name: SERVARR_ADMIN_USER
          value: "admin"
        - name: SERVARR_ADMIN_PASSWORD
          value: "adminpass"
        - name: SERVARR_API_KEY
          value: "97d741a13af015bf750f857a7e097f20"
        - name: CONFIG_PATH
          value: "/config/radarr-config.json"
        command: ["bun", "run", "dist/index.js", "--init"]
        volumeMounts:
        - name: radarr-config-volume
          mountPath: /config
        - name: radarr-config-file
          mountPath: /config/radarr-config.json
          subPath: radarr-config.json
      containers:
      - name: radarr
        image: linuxserver/radarr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "UTC"
        ports:
        - containerPort: 7878
        volumeMounts:
        - name: radarr-config-volume
          mountPath: /config
        - name: movies-storage
          mountPath: /movies
        readinessProbe:
          httpGet:
            path: /api/v3/system/status
            port: 7878
            httpHeaders:
            - name: X-Api-Key
              value: "97d741a13af015bf750f857a7e097f20"
          initialDelaySeconds: 60
          periodSeconds: 10
      - name: preparr-sidecar
        image: preparr:latest
        imagePullPolicy: Never
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres123"
        - name: POSTGRES_DB
          value: "radarr_main"
        - name: SERVARR_URL
          value: "http://localhost:7878"
        - name: SERVARR_TYPE
          value: "radarr"
        - name: SERVARR_ADMIN_USER
          value: "admin"
        - name: SERVARR_ADMIN_PASSWORD
          value: "adminpass"
        - name: SERVARR_API_KEY
          value: "97d741a13af015bf750f857a7e097f20"
        - name: CONFIG_PATH
          value: "/config/radarr-config.json"
        - name: CONFIG_WATCH
          value: "true"
        - name: CONFIG_RECONCILE_INTERVAL
          value: "30"
        - name: HEALTH_PORT
          value: "9001"
        - name: LOG_LEVEL
          value: "info"
        - name: QBITTORRENT_URL
          value: "http://qbittorrent:8080"
        - name: QBITTORRENT_USER
          value: "admin"
        - name: QBITTORRENT_PASSWORD
          value: "adminpass"
        command: ["bun", "run", "dist/index.js"]
        ports:
        - containerPort: 9001
        volumeMounts:
        - name: radarr-config-volume
          mountPath: /config
        - name: radarr-config-file
          mountPath: /config/radarr-config.json
          subPath: radarr-config.json
        readinessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: radarr-config-volume
        emptyDir: {}
      - name: radarr-config-file
        configMap:
          name: radarr-config
      - name: movies-storage
        emptyDir: {}