apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: preparr-test
spec:
  type: NodePort
  selector:
    app: sonarr
  ports:
    - name: webui
      port: 8989
      targetPort: 8989
      nodePort: 30989
    - name: health
      port: 9001
      targetPort: 9001
      nodePort: 31001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: preparr-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      initContainers:
      - name: preparr-init
        image: preparr:latest
        imagePullPolicy: Never
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres123"
        - name: POSTGRES_DB
          value: "servarr"
        - name: SERVARR_URL
          value: "http://sonarr:8989"
        - name: SERVARR_TYPE
          value: "sonarr"
        - name: SERVARR_ADMIN_USER
          value: "admin"
        - name: SERVARR_ADMIN_PASSWORD
          value: "adminpass"
        - name: SERVARR_API_KEY
          value: "2bac5d00dca43258313c734821a15c4c"
        - name: CONFIG_PATH
          value: "/config/sonarr-config.json"
        command: ["bun", "run", "dist/index.js", "--init"]
        volumeMounts:
        - name: sonarr-config-volume
          mountPath: /config
        - name: sonarr-config-file
          mountPath: /config/sonarr-config.json
          subPath: sonarr-config.json
      containers:
      - name: sonarr
        image: linuxserver/sonarr:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "UTC"
        ports:
        - containerPort: 8989
        volumeMounts:
        - name: sonarr-config-volume
          mountPath: /config
        - name: tv-storage
          mountPath: /tv
        readinessProbe:
          httpGet:
            path: /api/v3/system/status
            port: 8989
            httpHeaders:
            - name: X-Api-Key
              value: "2bac5d00dca43258313c734821a15c4c"
          initialDelaySeconds: 60
          periodSeconds: 10
      - name: preparr-sidecar
        image: preparr:latest
        imagePullPolicy: Never
        env:
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres123"
        - name: POSTGRES_DB
          value: "sonarr_main"
        - name: SERVARR_URL
          value: "http://localhost:8989"
        - name: SERVARR_TYPE
          value: "sonarr"
        - name: SERVARR_ADMIN_USER
          value: "admin"
        - name: SERVARR_ADMIN_PASSWORD
          value: "adminpass"
        - name: SERVARR_API_KEY
          value: "2bac5d00dca43258313c734821a15c4c"
        - name: CONFIG_PATH
          value: "/config/sonarr-config.json"
        - name: CONFIG_WATCH
          value: "true"
        - name: CONFIG_RECONCILE_INTERVAL
          value: "30"
        - name: HEALTH_PORT
          value: "9001"
        - name: LOG_LEVEL
          value: "info"
        command: ["bun", "run", "dist/index.js"]
        ports:
        - containerPort: 9001
        volumeMounts:
        - name: sonarr-config-volume
          mountPath: /config
        - name: sonarr-config-file
          mountPath: /config/sonarr-config.json
          subPath: sonarr-config.json
        readinessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 9001
          initialDelaySeconds: 60
          periodSeconds: 30
      volumes:
      - name: sonarr-config-volume
        emptyDir: {}
      - name: sonarr-config-file
        configMap:
          name: sonarr-config
      - name: tv-storage
        emptyDir: {}